server:
    port: 8080
spring:
  application:
    name: va-benefits-api
    
# Specifying the following key entries in mixed cases due to YAML/Spring-boot limitation...    
vaClaimIntakePointerUrl: https://sandbox-api.va.gov/services/vba_documents/v1/uploads
vaAuthHeaderKey: apikey
vaAuthHeaderValue: RrJGQZc6jpNp9NwKEn6GO2ZDq11MbdXm

performETagValidation: false

awsAccessKey: 
awsSecretKey: